name: si700_trabalho
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  scrollable_table_view: ^2.0.3
  google_fonts: ^6.2.1
  socket_io_client: ^3.0.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.4
  cloud_firestore: ^5.4.4
  firebase_analytics: ^11.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - google_fonts/

  # fonts:
  #   - family: Abhaya
  #     fonts:
  #       - asset: fonts/AbhayaLibre-Bold.ttf
  #       - asset: fonts/AbhayaLibre-ExtraBold.ttf
  #       - asset: fonts/AbhayaLibre-Medium.ttf
  #       - asset: fonts/AbhayaLibre-Regular.ttf
  #       - asset: fonts/AbhayaLibre-SemiBold.ttf
